id: P009635
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1189
  title: གཞུང་གསུམ་རབ་ཏུ་འབྱེད་པ་
  author: ''
  volumes:
    c5545685369b47fda47bdc0484730357:
      image_group_id: I1CZ1650
      title: ''
      volume_number: 1
      total_pages: 70
      base_file: v001.txt
