id: I2D9CCE99
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T16:38:19+00:00'
last_modified: '2022-06-08T12:26:17.084859+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1189
  title: གཞུང་གསུམ་རབ་ཏུ་འབྱེད་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF55:
      image_group_id: I1CZ1650
      title: ''
      total_pages: 70
      order: 1
      base_file: BF55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
