id: I2D9CCE99
legacy_id: P009635
ocr_import_info:
  bdrc_scan_id: W1CZ1189
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T16:37:48'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:59:10.632851+00:00'
last_modified: 2022-08-31 02:59:20.730201
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1189
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1189
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཞུང་གསུམ་རབ་ཏུ་འབྱེད་པ།
  author: གསེར་མདོག་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.4828147852322428
  ocr_word_median_confidence_index: 0.4300000071525574
quality: null
bases:
  I1CZ1650:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1650
      total_pages: 70
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1650.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.4828147852322428
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
